BaseProject/Controllers/DashBoard/RegionsController.cs
using BaseProject.Domain.Enums;
using BaseProject.Domain.ViewModel.Regions;
using BaseProject.Infrastructure.Extension;
using BaseProject.Services.DashBoard.Contract.RegionsInterfaces;
using Microsoft.AspNetCore.Mvc;

namespace BaseProject.Controllers.DashBoard
{
    [AuthorizeRolesAttribute(Roles.Admin, Roles.Regoins)]

    public class RegionsController : Controller
    {
        private readonly IRegionServices _regionServices;

        public RegionsController(IRegionServices regionServices)
        {
            _regionServices = regionServices;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            return View(await _regionServices.GetAllRegions());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.city = _regionServices.GetAllCities(); 
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateRegionViewModel createRegionViewModel)
        {
            if (ModelState.IsValid)
            {
                if(await _regionServices.CreateRegion(createRegionViewModel))
                    return RedirectToAction(nameof(Index));
            }
            return View(createRegionViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            var regoin = await _regionServices.GetRegionDetails(Id);
            if (regoin == null)
            {
                return NotFound();
            }
            ViewBag.city = _regionServices.GetAllCitiesWithSelectedCity(regoin.CityId);

            return View(regoin);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditRegionViewModel editRegionViewModel)
        {
            if (ModelState.IsValid)
            {
                if(await _regionServices.EditRegion(editRegionViewModel))
                    return RedirectToAction(nameof(Index));
            }

            return View(editRegionViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeState(int? id)
        {
            bool IsActive=await _regionServices.ChangeState(id);
            return Json(new { data = IsActive });
        }

    }
}

BaseProject/Views/Regions/Create.cshtml
@model BaseProject.Domain.ViewModel.Regions.CreateRegionViewModel

@{
    ViewData["Title"] = "اضافة حي";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">اضافة حي</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Create" enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NameAr" class="control-label">اسم الحي بالعربيه</label>
                    <input asp-for="NameAr" class="form-control" />
                    <span asp-validation-for="NameAr" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NameEn" class="control-label">اسم الحي بالانجليزيه</label>
                    <input asp-for="NameEn" class="form-control" />
                    <span asp-validation-for="NameEn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CityId" class="control-label">المدينة</label>
                    <select asp-for="CityId"
                            class="form-control"
                            asp-items="@ViewBag.city">
                        <option value="0" selected="selected">من فضلك اختر مدينتك</option>
                    </select>
                    <span asp-validation-for="CityId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn-new-style btn-rounded" />
                </div>
                <div>
                    <a asp-controller="Regions" asp-action="Index" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BaseProject/Views/Regions/Edit.cshtml
@model BaseProject.Domain.ViewModel.Regions.EditRegionViewModel

@{
    ViewData["Title"] = "تعديل حي";
}

<div class="card-box">
    <h2 class="header-title m-t-0 m-b-30">تديل حي</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Edit" enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NameAr" class="control-label">اسم الحي بالعربيه</label>
                    <input asp-for="NameAr" class="form-control" />
                    <span asp-validation-for="NameAr" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NameEn" class="control-label">اسم الحي بالانجليزيه</label>
                    <input asp-for="NameEn" class="form-control" />
                    <span asp-validation-for="NameEn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CityId" class="control-label">المدينة</label>
                    <select asp-for="CityId"
                            class="form-control"
                            asp-items="@ViewBag.city">
                        <option value="0" selected="selected">من فضلك اختر مدينتك</option>
                    </select>
                    <span asp-validation-for="CityId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="تعديل" class="btn-new-style btn-rounded" />
                </div>
                <div>
                    <a asp-controller="Regions" asp-action="Index" class="btn-black">العودة الى الرئيسية</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BaseProject/Views/Regions/Index.cshtml
@model IEnumerable<BaseProject.Domain.ViewModel.Regions.RegionsViewModel>
@{
    ViewData["Title"] = "الأحياء";
}


<div class="card-box">

    <h2 class="header-title m-t-0 m-b-30">الأحياء</h2>

    <div>
        <p>
            <a asp-action="Create" asp-controller="Regions" class="btn btn-primary btn-rounded w-md waves-effect waves-light m-b-5">اضافة حي</a>
        </p>

        <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>اسم الحي بالعربيه</th>
                    <th>اسم الحي بالانجليزيه</th>
                    <th>اسم المدينة </th>
                    <th> الحالة </th>
                    <th>تغيير الحالة </th>
                    <th>تعديل </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameAr)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameEn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CityName)
                        </td>
                        <td>
                            @{
                                if (item.IsActive == true)
                                {
                                    <label id="@item.Id" style="color:green;font-size: 17px;">مفعل</label>
                                }
                                else
                                {
                                    <label id="@item.Id" style="color:red;font-size: 17px;">غير مفعل</label>
                                }
                            }
                        </td>
                        <td>
                            <input type="button" value="تغيير الحالة" onclick="Validation('@item.Id')" class="btn btn-purple btn-rounded" />
                        </td>

                        <td>
                            <a asp-action="Edit" asp-controller="Regions" asp-route-Id="@item.Id" class="btn btn-info btn-rounded">تعديل</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- -------------------------------------------------------------------------------------------------- -->
    </div><!-- end row -->
</div>


@section scripts{
    <script>

        function Validation(id) {
            $.ajax({
                url: "/Regions/ChangeState",
                type: "POST",
                dataType: "json",
                data: {
                    id: id
                },
                success: function (result) {

                    if (result.data == true) {
                        $('#' + id).css('color', 'green');
                        $('#' + id).html('مفعل');
                    } else if (result.data == false) {
                        $('#' + id).css('color', 'red');
                        $('#' + id).html('غير مفعل');
                    }
                },
                failure: function (info) {

                }
            });
        }

    </script>
}